# Generated by Django 4.1.5 on 2023-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_hodim_stavka"),
    ]

    operations = [
        migrations.AddField(
            model_name="ombor",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tranzaksiyacategory",
            name="status",
            field=models.CharField(
                choices=[("kirim", "kirim"), ("chiqim", "chiqim")],
                default=1,
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ombor",
            name="olchov",
            field=models.FloatField(
                blank=True,
                help_text="Necha kg lik yoki metr lik ekani haqida ...",
                null=True,
            ),
        ),
    ]
